// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/diegosperes/cachex (interfaces: Policy)
//
// Generated by this command:
//
//	mockgen -destination=mock_policy_test.go -package=cachex_test -typed github.com/diegosperes/cachex Policy
//

// Package cachex_test is a generated GoMock package.
package cachex_test

import (
	reflect "reflect"

	cachex "github.com/diegosperes/cachex"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicy is a mock of Policy interface.
type MockPolicy[K comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyMockRecorder[K]
	isgomock struct{}
}

// MockPolicyMockRecorder is the mock recorder for MockPolicy.
type MockPolicyMockRecorder[K comparable] struct {
	mock *MockPolicy[K]
}

// NewMockPolicy creates a new mock instance.
func NewMockPolicy[K comparable](ctrl *gomock.Controller) *MockPolicy[K] {
	mock := &MockPolicy[K]{ctrl: ctrl}
	mock.recorder = &MockPolicyMockRecorder[K]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicy[K]) EXPECT() *MockPolicyMockRecorder[K] {
	return m.recorder
}

// Admit mocks base method.
func (m *MockPolicy[K]) Admit(key K) (cachex.Entry[K], cachex.Entry[K], bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Admit", key)
	ret0, _ := ret[0].(cachex.Entry[K])
	ret1, _ := ret[1].(cachex.Entry[K])
	ret2, _ := ret[2].(bool)
	return ret0, ret1, ret2
}

// Admit indicates an expected call of Admit.
func (mr *MockPolicyMockRecorder[K]) Admit(key any) *MockPolicyAdmitCall[K] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Admit", reflect.TypeOf((*MockPolicy[K])(nil).Admit), key)
	return &MockPolicyAdmitCall[K]{Call: call}
}

// MockPolicyAdmitCall wrap *gomock.Call
type MockPolicyAdmitCall[K comparable] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyAdmitCall[K]) Return(admitted, evicted cachex.Entry[K], ok bool) *MockPolicyAdmitCall[K] {
	c.Call = c.Call.Return(admitted, evicted, ok)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyAdmitCall[K]) Do(f func(K) (cachex.Entry[K], cachex.Entry[K], bool)) *MockPolicyAdmitCall[K] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyAdmitCall[K]) DoAndReturn(f func(K) (cachex.Entry[K], cachex.Entry[K], bool)) *MockPolicyAdmitCall[K] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Capacity mocks base method.
func (m *MockPolicy[K]) Capacity() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capacity")
	ret0, _ := ret[0].(int)
	return ret0
}

// Capacity indicates an expected call of Capacity.
func (mr *MockPolicyMockRecorder[K]) Capacity() *MockPolicyCapacityCall[K] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capacity", reflect.TypeOf((*MockPolicy[K])(nil).Capacity))
	return &MockPolicyCapacityCall[K]{Call: call}
}

// MockPolicyCapacityCall wrap *gomock.Call
type MockPolicyCapacityCall[K comparable] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyCapacityCall[K]) Return(arg0 int) *MockPolicyCapacityCall[K] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyCapacityCall[K]) Do(f func() int) *MockPolicyCapacityCall[K] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyCapacityCall[K]) DoAndReturn(f func() int) *MockPolicyCapacityCall[K] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Remove mocks base method.
func (m *MockPolicy[K]) Remove(e cachex.Entry[K]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", e)
}

// Remove indicates an expected call of Remove.
func (mr *MockPolicyMockRecorder[K]) Remove(e any) *MockPolicyRemoveCall[K] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockPolicy[K])(nil).Remove), e)
	return &MockPolicyRemoveCall[K]{Call: call}
}

// MockPolicyRemoveCall wrap *gomock.Call
type MockPolicyRemoveCall[K comparable] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyRemoveCall[K]) Return() *MockPolicyRemoveCall[K] {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyRemoveCall[K]) Do(f func(cachex.Entry[K])) *MockPolicyRemoveCall[K] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyRemoveCall[K]) DoAndReturn(f func(cachex.Entry[K])) *MockPolicyRemoveCall[K] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Reset mocks base method.
func (m *MockPolicy[K]) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockPolicyMockRecorder[K]) Reset() *MockPolicyResetCall[K] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockPolicy[K])(nil).Reset))
	return &MockPolicyResetCall[K]{Call: call}
}

// MockPolicyResetCall wrap *gomock.Call
type MockPolicyResetCall[K comparable] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyResetCall[K]) Return() *MockPolicyResetCall[K] {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyResetCall[K]) Do(f func()) *MockPolicyResetCall[K] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyResetCall[K]) DoAndReturn(f func()) *MockPolicyResetCall[K] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Size mocks base method.
func (m *MockPolicy[K]) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockPolicyMockRecorder[K]) Size() *MockPolicySizeCall[K] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockPolicy[K])(nil).Size))
	return &MockPolicySizeCall[K]{Call: call}
}

// MockPolicySizeCall wrap *gomock.Call
type MockPolicySizeCall[K comparable] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicySizeCall[K]) Return(arg0 int) *MockPolicySizeCall[K] {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicySizeCall[K]) Do(f func() int) *MockPolicySizeCall[K] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicySizeCall[K]) DoAndReturn(f func() int) *MockPolicySizeCall[K] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Touch mocks base method.
func (m *MockPolicy[K]) Touch(e cachex.Entry[K]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Touch", e)
}

// Touch indicates an expected call of Touch.
func (mr *MockPolicyMockRecorder[K]) Touch(e any) *MockPolicyTouchCall[K] {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockPolicy[K])(nil).Touch), e)
	return &MockPolicyTouchCall[K]{Call: call}
}

// MockPolicyTouchCall wrap *gomock.Call
type MockPolicyTouchCall[K comparable] struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyTouchCall[K]) Return() *MockPolicyTouchCall[K] {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyTouchCall[K]) Do(f func(cachex.Entry[K])) *MockPolicyTouchCall[K] {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyTouchCall[K]) DoAndReturn(f func(cachex.Entry[K])) *MockPolicyTouchCall[K] {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
